name: pr-since

on:
  pull_request:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
  test:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
      - run: yarn test:since
